language: r
r: 
    #- bioc-devel
    - bioc-release
warnings_are_errors: false # :ToDo: comment out
sudo: false
cache: packages

r_packages:
  - covr
  - testthat
  - knitr
  - rmarkdown

os:
  - linux
    #  - osx

bioc_required: true
bioc_packages:
  - BiocCheck
  - KEGGREST

after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"
 
after_success:
  - Rscript -e 'covr::codecov()'

# Something happend to osx bioc-devel builds 
matrix:
  exclude:
  - os: osx
    r: bioc-devel

env:
  - PATH="$HOME/bin:$PATH"
  - JDK=openjdk8

# for loading cplex libraries
before_install:
  - jdk_switcher use $JDK
  - mkdir ~/lib
  - test -n "${CPLEX_SO_LINK}" && wget -q "${CPLEX_SO_LINK}" -O ~/lib/libcplex1263.so
  - wget https://github.com/ctlab/sgmwcs-solver/releases/download/v0.9.2/sgmwcs-solver.jar -O ~/lib/sgmwcs.jar
  - mkdir -p ~/bin
  - echo -e '#!/bin/sh\nexec java -Djava.library.path=$HOME/lib -Xmx2G -jar $HOME/lib/sgmwcs.jar -i "$@"' > ~/bin/sgmwcs
  - chmod a+x ~/bin/sgmwcs
  - ~/bin/sgmwcs -h
  - sgmwcs -h

dist: trusty
